### ISSUE TITLE
您好又有一个新问题就是在getAnswer()函数中会报错，请问这个该怎么解决？

### ISSUE THREAD

**Issue by eeee0717** [amdoi7/zjoocTool#2]
![image](https://user-images.githubusercontent.com/70054568/161416720-3feb2cbf-2db6-4b15-84ad-f37b2ab7a220.png)
您好又有一个新问题就是在getAnswer()函数中会报错，请问这个该怎么解决？

**Comment by amdoi7** [comment]
用现在的代码试一试
