### ISSUE TITLE
您好我想问下这个状态

### ISSUE THREAD

**Issue by Summmmmmary** [amdoi7/zjoocTool#4]
在.py的37行填写了对应账密 运行后返回值含有 'courseProcessStatus': 0
可是课程已经自己刷完了，为什么进度是0呢？

完整返回结果  {'id': 0, 'courseId': '2c9180827e52dbc8017f0a47d4c91bf8', 'courseName': '生物药物检测技术', 'courseBatchId': '20220', 'courseProcessStatus': 0}

对了调用的ddddocr库必须运行在python 3.9 及以下，希望能在描述文件里加一下，谢谢

**Comment by Summmmmmary** [comment]
<img src="https://s1.328888.xyz/2022/05/04/hI4vF.png" alt="screen" border="0">

**Comment by amdoi7** [comment]
这个我没有仔细研究过，搞完网课后就没看过了。这个courseProcessStatus  翻译过来应该是课程进行状态吧  返回值为0 可能表示该课程正在学习中？（大雾
 

对了感谢你的提醒，已加说明。

**Comment by Summmmmmary** [comment]
但是为什么，刷不了课呀，一直是这个状态，依赖已经都装上了

**Comment by Summmmmmary** [comment]
我为了验证是不是我的问题特地新加了一门课然后运行，但是还是这个界面，就多了一行新选的课程名称，我想知道项目跑起来是啥样的，总不能就像我上面的图一样吧

**Comment by amdoi7** [comment]
兄弟 main 函数里面 解除相应代码注释 再运行😓

**Comment by Summmmmmary** [comment]
我没细看，对不起对不起呜呜，然后答题考试的坑还填嘛

**Comment by amdoi7** [comment]
还有什么坑吗？截图说一下

**Comment by amdoi7** [comment]
3285109133 你加我QQ问吧，反正我今天比较闲。😓
